### ISSUE TITLE
Error when loading prover

### ISSUE THREAD

**Issue by identicalsnowflake** [idris-hackers/idris-mode#330] opened 2015-04-26 18:53 UTC
I tried uninstalling and reinstalling idris-mode from Melpa, but I still have this issue: any time I try to access the theorem prover, I get an error which says ```"error in process filter: no buffer named *idris-proof-script*"```

**Comment by david-christiansen** [comment] 2015-04-27 08:26
I can't reproduce this locally with the latest versions of Idris and `idris-mode`. It works fine here.

Can I get you to provide a bit more information? In particular, would you please paste the source file you're working with into a comment and then describe exactly how you're launching the prover? As in, what keys you're pressing or what buttons you're clicking or what commands you're issuing at the REPL?

Thanks!

**Comment by identicalsnowflake** [comment] 2015-04-28 17:03
I've probably messed up my configuration somehow. Anyway, I just create a new directory, make a new file test.idr, type some code with a theorem like this:

```idris

import Data.So

test : (n:Nat) -> So (n+1 > n)
```

C+x C+s to save, C+c C+l to load up Idris. It notices a theorem and asks me if I want to prove it (with the little [p] button). I click [p] and I get the error described above.

It's a bit strange, since everything else works fine -- I can execute my functions in the idris-mode repl, I can type check my files. Everything works for me except the theorem prover.

**Comment by identicalsnowflake** [comment] 2015-04-28 17:04
Accidentally hit close and comment instead of comment.

**Comment by david-christiansen** [comment] 2015-04-28 17:07
Could you please paste the contents of the *idris-events* buffer?

**Comment by identicalsnowflake** [comment] 2015-04-28 20:33
```
		 ((:tt-term "AAAAAAAAAAEAAAAAAAAAAAFuAAMAAwAAAAAACAABAQAAAAAAAAAAAlNvAAAAAAAAAAIAAAAAAAAAAlNvAAAAAAAAAAREYXRhAwMDAwABAQAAAAAAAAAAAT4AAAAAAAAAAgAAAAAAAAAHQ2xhc3NlcwAAAAAAAAAHUHJlbHVkZQADAAAAAAAIAAABAAAAAAAAAAADTmF0AAAAAAAAAAIAAAAAAAAAA05hdAAAAAAAAAAHUHJlbHVkZQABAQQBAQAAAAAAAAAAA09yZAAAAAAAAAACAAAAAAAAAAdDbGFzc2VzAAAAAAAAAAdQcmVsdWRlAAAAAAAAAAEAAAAAAAAAA05hdAAAAAAAAAACAAAAAAAAAANOYXQAAAAAAAAAB1ByZWx1ZGUDAwMDAAEBAAAAAAAAAAABKwAAAAAAAAACAAAAAAAAAAdDbGFzc2VzAAAAAAAAAAdQcmVsdWRlAAMAAAAAAAgAAAEAAAAAAAAAAANOYXQAAAAAAAAAAgAAAAAAAAADTmF0AAAAAAAAAAdQcmVsdWRlAAEBBAEBAAAAAAAAAAADTnVtAAAAAAAAAAIAAAAAAAAAB0NsYXNzZXMAAAAAAAAAB1ByZWx1ZGUAAAAAAAAAAQAAAAAAAAADTmF0AAAAAAAAAAIAAAAAAAAAA05hdAAAAAAAAAAHUHJlbHVkZQAAAAAAAAAAAAABbgMDAwABAQAAAAAAAAAAC2Zyb21JbnRlZ2VyAAAAAAAAAAIAAAAAAAAAB0NsYXNzZXMAAAAAAAAAB1ByZWx1ZGUAAwAAAAAACAAAAQAAAAAAAAAAA05hdAAAAAAAAAACAAAAAAAAAANOYXQAAAAAAAAAB1ByZWx1ZGUAAQEEAQEAAAAAAAAAAANOdW0AAAAAAAAAAgAAAAAAAAAHQ2xhc3NlcwAAAAAAAAAHUHJlbHVkZQAAAAAAAAABAAAAAAAAAANOYXQAAAAAAAAAAgAAAAAAAAADTmF0AAAAAAAAAAdQcmVsdWRlBAEAAAAAAQAAAAAAAAAAAAABbg=="))))))))
 7)
23:31:25 -> ((:interpret ":consolewidth 100")
 8)
23:31:25 <- (:return
 (:ok "")
 8)
23:31:29 -> ((:interpret ":p Main.test")
 9)
23:31:29 <- (:set-prompt "*test" 9)
23:31:29 <- (:abandon-proof "Abandoned" 9)
```

**Comment by david-christiansen** [comment] 2015-05-12 20:46
OK, so this is a bug in the user interface of `idris-mode`. Not everything that shows up as a metavar can be used in the prover - only things that are specifically introduced as `?var`. If you add the line `test n = ?test_rhs`, then the prover opens fine for `test_rhs`. Really, it just shouldn't show the `[P]` button on invalid metavariables, or perhaps not even show them in the list.

Thanks for a good report!

**Comment by david-christiansen** [comment] 2015-05-18 09:31
OK, so it seems that this is something that needs to be fixed in the compiler - the non-IDE mode prevents starting the prover where it doesn't belong. This should also happen in IDE mode.

**Closed** 2015-05-18 10:24 UTC
Labels: confirmed
