### ISSUE TITLE
C-c C-l overwrites Idris code buffer with compiler messages and changes major mode

### ISSUE THREAD

**Issue by kevinsullivan** [idris-hackers/idris-mode#401] opened 2015-09-19 04:40 UTC
I suspect the problem is due to some configuration issue on my end, possibly to other minor modes being turned on, but I have ample confirmation this is happening. 

Here's what happens. One is editing code in emacs mode. One then hits C-c C-l to compile/reload. What happens then is that either (1) the code buffer is blanked and also the major mode switches to Compiler Message, or (2) actual compiler messages overwrite the code and the major model also switches. In the first case, an emacs undo reverts to the code buffer. In the second case, that doesn't work. One has to exit emacs and reopen the code file to get editing again (and hope that the code was recently saved into the file). 

It's not clear yet exactly what circumstances cause the problem, but it is happening frequently enough that it's definitely a problem (possibly only on our end, but it is a problem for us, for sure).

I thought that perhaps this was due to a mismatch betwen Idris and Idris-mode versions, so tonight I installed the new (v. 19.1) Idris from Hackage, pointed my path to the new version, and did a package update in emacs, which among other packages downloaded the current version of idris-mode.

Yet when editing code tonight, I witnessed the problem again. If there are any suggestions as to how to diagnose/debug this problem, that'd be great.

**Comment by david-christiansen** [comment] 2015-09-19 07:06
A different Idris version is unlikely to make something like this happen. So it sounds like what's happening is that compiler messages, instead of being displayed in their own dedicated buffer, are somehow being displayed in the code buffer. The first step of the display process is to blank the buffer (getting rid of obsolete error messages), so that makes sense here.

The function that does this is `idris-list-compiler-notes`. That's where I'd start looking. Perhaps check to see if `idris-notes-buffer-name` is getting changed?

Would you mind pasting all the Idris-relevant and buffer-management-relevant parts of your `init.el`? Or even the whole thing if you're comfortable with that?

In the meantime, for your course you could use Atom instead of Emacs. The Atom mode is perfectly reasonable - it has a slightly fewer features, but all the truly important stuff is there.

**Comment by kevinsullivan** [comment] 2015-09-19 09:29
David, Thanks. I will focus on init.el. A bunch of stuff is getting loaded. I'll back that out and see what happens. In the meantime, might you point me at the relevant config files for Atom, so I can evaluate. I've not used Atom before.

**Comment by david-christiansen** [comment] 2015-09-19 09:47
You shouldn't need any config files for Atom. If you open it up and look in the settings, there's a package installer, and Idris is in the repository.

It's developed at https://github.com/idris-hackers/atom-language-idris by @archaeron - he's done a great job!

**Comment by archaeron** [comment] 2015-09-19 10:29
Thanks @david-christiansen :)
If you do use it @kevinsullivan I'm always glad for bug reports if you find oneone (or feature requests)

**Comment by kevinsullivan** [comment] 2015-09-29 05:03
Thanks @archaeron. I've moved a bunch of students over to Atom.

In the meantime, I've started trying to isolate the problem in idris-mode.

To begin with, I've simply removed my init.el file. I do have idris-mode and some other packages loaded, so when I open an Idris file, I end up in idris-mode with Ind and ElDoc also enabled as minor modes.

I don't know that this is related, but it might be. When I do C-c C-l to attempt to load a program with a syntax error (see sample code below), I get an error message in a separate window, but something is also modifying my code buffer, by adding a single blank line at the end. Each time I run C-c C-l I get another line added at the end of the file. I also see these little "angle-iron" characters at the bottom of my code buffer when this is happening. They seem to properly belong to the idris-messages subsystem, but I could be wrong about that. In any case, it seems the compilation process is writing into my code buffer, though it's not currently overwriting it. Is anyone else seeing this behavior? Here's the broken code for which C-c C-l adds lines to my code buffer:

data foo = bar | baz
buj: foo -> foo
buj bar = ((baz)

**Comment by david-christiansen** [comment] 2015-09-29 06:01
From my command line:
```
davidc@gungnir:~$ emacs --version
GNU Emacs 24.4.1
Copyright (C) 2014 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
davidc@gungnir:~$ emacs -q
```

Then an emacs window opens with the default configuration (`-q` means skip the init file).

In this file, I locate a checkout of `idris-mode` to load, and put it on my `load-path` manually:
`C-x b *scratch* RET` switches to `*scratch*`, in which I write `(add-to-list 'load-path "~/Code/el/idris-mode/")` and then press `C-j` at the end of the line to evaluate it. Now Emacs can see `idris-mode`'s source. Then I type `(add-to-list 'load-path "~/Code/el/prop-menu/")` to get a dependency, and then `(require 'idris-mode)` to load it.

Now we have the cleanest and simplest possible configuration with `idris-mode`. I then do `C-x C-f ~/tmp/issue401.idr RET` and paste in your code. It seems that in this specific case, Idris is reporting an error location back to Emacs that is beyond the end of the file by one character, so `idris-mode` adds a space for the red underlining of the syntax error to the place where it was reported. This is on line 103 of `idris-warnings.el`. Probably, the Idris parser should instead report mismatching parentheses at the last non-whitespace that it saw. Note that the space-adding does not occur if `buj` isn't the last definition.

At no time is code being deleted in this test - all that happens is a space is inserted so that the error can be highlighted. I may be able to remove this particular error reporting hack - let me play with some solutions. It may also be the case that we shouldn't show the underlines at all in this case, but because it's possible to use `idris-mode` with those as the only error report mechanism, this might not be a good idea. In the meantime, what do you mean by "angle-iron"? Could you take a screenshot? Can you find an example where code is overwritten, rather than having a space placed onto an empty line during error reporting?

Potential replacements for the empty error line hack:
 1. Show all underlined error regions with a red X or something similar at the beginning
 2. Instead of inserting the space, make it look as though the region has a space in it until the error is fixed, but don't actually put it there
 3. Use a fringe bitmap to indicate lines with errors (which requires that the fringe is enabled and the Emacs is graphical IIRC)

Probably number 2 is best of these.

**Comment by david-christiansen** [comment] 2015-09-29 06:02
But there still doesn't seem to be any way to replicate code being overwritten, rather than having a space inserted on an empty line, which never makes Idris code invalid.

**Comment by david-christiansen** [comment] 2015-09-29 06:22
Oh, and the reason for my pedantic walkthrough of loading Emacs without a config file was so that you can keep your `init.el` and still test things in a clean config :-)

**Comment by abailly** [comment] 2018-02-10 18:09
@david-christiansen @kevinsullivan Should we close the issue as non-reproducible?

**Closed** 2018-02-11 01:26 UTC
